# Generated by Django 5.1.3 on 2024-12-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='gender',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='gender',
            field=models.ManyToManyField(blank=True, to='EligibleChecker.gender'),
        ),
    ]
