# Generated by Django 5.1.3 on 2024-12-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0005_populating_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='degree_classification',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='min_gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.DeleteModel(
            name='ClassificationDegree',
        ),
    ]
