# Generated by Django 5.1.3 on 2025-01-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0006_remove_scholarship_degree_classification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='degree_attained',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='degreelevel',
            field=models.ManyToManyField(blank=True, to='EligibleChecker.degreelevel'),
        ),
    ]
