# Generated by Django 5.1.3 on 2025-01-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0007_degreelevel_remove_scholarship_degree_attained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='work_experience',
            field=models.PositiveIntegerField(),
        ),
    ]
