# Generated by Django 5.1.3 on 2025-01-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0008_alter_scholarship_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='location',
            field=models.CharField(default='Default', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
