# Generated by Django 5.1.3 on 2025-01-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0009_scholarship_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
