# Generated by Django 5.1.3 on 2025-01-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0011_customuser_degree_level_customuser_field_of_study_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='min_gpa',
            new_name='gpa',
        ),
    ]
