# Generated by Django 5.1.3 on 2025-02-13 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0012_rename_min_gpa_customuser_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('criteria', models.TextField()),
                ('duration', models.CharField(max_length=10)),
                ('min_cluster_points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=50)),
                ('contact_info', models.TextField()),
                ('website_link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='degreelevel',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='degree_level',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='work_experience',
        ),
        migrations.CreateModel(
            name='SavedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EligibleChecker.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='EligibleChecker.university'),
        ),
        migrations.DeleteModel(
            name='Citizenship',
        ),
        migrations.DeleteModel(
            name='DegreeLevel',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
