# Generated by Django 5.1.3 on 2025-02-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0013_program_university_remove_customuser_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedprogram',
            unique_together={('user', 'program')},
        ),
    ]
