# Generated by Django 5.1.3 on 2025-02-17 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0014_alter_savedprogram_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='university',
            name='Email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='phone_number',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
    ]
