# Generated by Django 5.1.3 on 2025-02-24 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0015_remove_university_contact_info_university_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='program',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='program',
            name='min_cluster_points',
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('degree', "Bachelor's Degree"), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=100)),
                ('entry_requirements', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_types', to='EligibleChecker.program')),
            ],
        ),
    ]
