# Generated by Django 5.1.3 on 2025-02-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0016_remove_program_criteria_remove_program_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='description',
        ),
        migrations.AddField(
            model_name='university',
            name='campus',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
