# Generated by Django 5.1.3 on 2025-02-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0018_alter_university_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
