# Generated by Django 5.1.3 on 2025-02-25 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0019_alter_university_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtype',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_types', to='EligibleChecker.university'),
        ),
    ]
