# Generated by Django 5.1.3 on 2025-02-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0020_programtype_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='university_logo',
            field=models.ImageField(blank=True, null=True, upload_to='university_logos/'),
        ),
    ]
