# Generated by Django 5.1.3 on 2025-03-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0021_university_university_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='department',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
