# Generated by Django 5.1.3 on 2025-03-19 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0022_university_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='university',
            name='department',
        ),
        migrations.RemoveField(
            model_name='university',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='university',
            name='website_link',
        ),
        migrations.AddField(
            model_name='programtype',
            name='Email',
            field=models.EmailField(default='default', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programtype',
            name='department',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programtype',
            name='phone_number',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programtype',
            name='website_link',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
    ]
