# Generated by Django 5.1.3 on 2025-03-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EligibleChecker', '0023_remove_university_email_remove_university_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='main_email',
            field=models.EmailField(default='default', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='main_phone_number',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='main_website_link',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
    ]
